name: ${project.name}
main: net.plazmix.cases.PlazmixCasesPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

author: PlazmixDevelopmentTeam

depend: [PlazmixAPI]
